defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local

# snapshot
save_snapshot: true
load_snap: ""

# replay buffer
num_workers: 0
batch_size: 32
train_steps: 100001
eval_freq: 20000

# misc
seed: 1
device: cuda

# experiment
experiment: train_model
model: derail
wandbuser:
wandbproject:

# data
dataset: D4RL/kitchen/complete-v2
datapath:
doaug: "none"
use_achieved_goal: false

agent:
  _target_: vip.models.model_derail.StateEuclideanDERAIL
  device: ${device}
  lr: 1e-4
  hidden_dim: 32
  size: 0
  mlp_width: 64
  l2weight: 0.01
  l1weight: 0.01
  conservative_weight: 0.2
  gamma: 0.9
  num_negatives: 0